language: node_js

node_js:
  - '0.10'
  - '0.11'

branches:
  only:
    - master

sudo: false

cache:
  directories:
    - /home/travis/.npm
    - /home/travis/.cache/bower
    - node_modules
    - bower_components

matrix:
  allow_failures:
    - node_js: '0.11'

  fast_finish: true

install:
  - npm install
  - bower install

script:
  - gulp lint:ci
  - gulp karma:ci
  - gulp karma:integration1x
  - gulp karma:integration2x
